# Generated by Django 5.2.12 on 2026-03-06 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_alter_option_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeScoringBand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('min_age_months', models.PositiveIntegerField()),
                ('max_age_months', models.PositiveIntegerField()),
                ('low_max', models.PositiveIntegerField(default=30)),
                ('mild_max', models.PositiveIntegerField(default=60)),
                ('moderate_max', models.PositiveIntegerField(default=100)),
            ],
            options={
                'ordering': ['min_age_months', 'max_age_months', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentDraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('respondent_name', models.CharField(blank=True, default='', max_length=200)),
                ('respondent_role', models.CharField(blank=True, default='', max_length=100)),
                ('respondent_email', models.EmailField(blank=True, default='', max_length=254)),
                ('child_age_months', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('responses', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgeBandCategoryWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('multiplier', models.FloatField(default=1.0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.questioncategory')),
                ('age_band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.agescoringband')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('age_band', 'category'), name='unique_age_band_category_weight')],
            },
        ),
    ]
